gha: Add envoy minor version tag in docker
cilium/proxy pull request #148
Opened 2023-03-18 11:13 UTC by sayboras

This is to add one more tag for docker artifact, following the below convention.

```
quay.io/cilium/cilium-envoy:v1.24-<commit-sha>
```

2023-03-20 10:35 UTC, jrajahalme requested changes
Some overlap with #147 that needs to be cleared up.

2023-03-20 10:35 UTC, jrajahalme commented on .github/workflows/build-envoy-images-release.yaml
> +          echo "quay.io/${{ github.repository_owner }}/cilium-envoy:${{ env.ENVOY_MINOR_RELEASE }}-${{ github.sha }}"
Should print out the "@<digest>" also for the new line so the full reference is easy to cut&paste?

2023-03-20 10:35 UTC, jrajahalme commented on .github/workflows/build-envoy-images-release.yaml
> +            quay.io/${{ github.repository_owner }}/cilium-envoy:${{ env.ENVOY_MINOR_RELEASE }}-${{ github.sha }}
This change is also in PR #147, but there you also remove the "latest" tag... Would it be possible to keep the `latest` tag for the latest `master` build, and not overwrite `latest` tag in any non-master builds?

2023-03-22 06:44 UTC, sayboras commented
Marking this one as draft

2023-04-03 15:22 UTC, michi-covalent approved these changes

2023-04-04 00:24 UTC, merged